### ISSUE TITLE
Initializing ClientContext while impersonating

### ISSUE THREAD

**Issue by valorl** [antiduh/nsspi#15]
Hi,

I am trying to use NSSPI to manually facilitate double-hop with Kerberos inside a custom OWIN and IIS based reverse-proxy/API Gateway.

My code looks something like this:
```csharp
var identity = (WindowsIdentity) context.Request.User.Identity;
using (var impersonation = identity.Impersonate())
{
    var clientCredentials = new ClientCurrentCredential(PackageNames.Kerberos);
    var client = new ClientContext(
        clientCredentials,
        "HTTP/" + backendHostname, // e.g. HTTP/myapi.mydomain.com
        ContextAttrib.MutualAuth |
        ContextAttrib.InitIdentify |
        ContextAttrib.Confidentiality |
        ContextAttrib.ReplayDetect |
        ContextAttrib.SequenceDetect |
        ContextAttrib.Connection |
        ContextAttrib.Delegate
    );
    var clientStatus = client.Init(null, out var tokenBytes);
    var token = Convert.ToBase64String(tokenBytes);
    context.Request.Headers.Append("Negotiate", token);
}
```
However the `client.Init()` call fails saying `No credentials are available in the security package`. Without the impersonation context, I'm able to get a token just fine. The SPNs should be set up correctly, and the app that's doing the impersonation is trusted in AD for Kerberos delegation. The `ImpersonationLevel` of the impersonated identity is `Impersonation` not `Delegation`.

I was hoping someone here might have a better insight into this and maybe see what I might be doing wrong, thanks.

**Comment by zoltanharmath** [comment]
What is the reply back from the KDC? Run a network trace on your server and watch the Kerberosv5 traffic between your server and the KDC. Is there any unexpected answer back from the KDC?

**Comment by valorl** [comment]
The problem was the `InitIdentify` flag. I'm not sure what exact purpose should that flag serve, but I noticed in the code (https://github.com/antiduh/nsspi/blob/master/NSspi/Contexts/ContextAttrib.cs#L119) that the enum has the same value as `AcceptIntegrity`. Since this was for client-side token initialization I just assumed that `AcceptIntegrity` was shadowing it, so I removed `InitIdentify` and used `InitIntegrity` instead and it worked.

Could you maybe explain (or point me to something) why are there "aliases" for the same value and what do the `Identify` ones mean ?

**Comment by antiduh** [comment]
Hi @valorl - that enumeration is an aggregation of the flags that can be sent to SSPI functions [AcceptSecurityContext ](https://docs.microsoft.com/en-us/windows/desktop/api/sspi/nf-sspi-acceptsecuritycontext)and [InitializeSecurityContext](https://docs.microsoft.com/en-us/windows/desktop/api/sspi/nf-sspi-initializesecuritycontexta).

Take a look at the documentation about the flags that can be sent.
