### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by romerod** [antiduh/nsspi#2]
Hello and thank you for implementing this wrapper, 

what do you think of deploying it as a nuget package?

Kind regards
Daniel

**Comment by antiduh** [comment]
Yeah, that's something I can do. I'll admit I've not yet touched nuget; have a decent getting-started reference?

**Comment by thoemmi** [comment]
@antiduh I'd like to support you with creating a NuGet package. For documentation, see https://docs.nuget.org/

**Comment by antiduh** [comment]
Hey, @thoemmi and @romerod, I've published a nuget package while I have a few spare minutes. It's fairly bare-bones until I take some time to dig into better nuget practices but hopefully it'll work. Let me know if you have any issues.
