### ISSUE TITLE
ServerContext does not contain a definition for GetRemoteIdentity

### ISSUE THREAD

**Issue by darshanmodh** [antiduh/nsspi#21]
With latest PR changes, I tried to start the TestServer project in visual studio and I got the build error for TestServer project. The error is saying: 

"'ServerContext' does not contain a definition for 'GetRemoteIdentity' and no accessible extension method 'GetRemoteIdentity' accepting a first argument of type 'ServerContext' could be found (are you missing a using directive or an assembly reference?)"

Seems like code is not retrieving remoteId as expected on this line: https://github.com/antiduh/nsspi/blob/master/TestServer/ServerForm.cs#L180

**Comment by antiduh** [comment]
Thanks for noticing. It's all better.
