### ISSUE TITLE
Validating client credentials against a "non current" AD.

### ISSUE THREAD

**Issue by Hochman85** [antiduh/nsspi#24]
I am able to authenticate and validate username / password against the current AD (I am authenticated to). But only for testing purpose, I'd like to force use another AD (not the one am authenticated against) with other credentials. Is that route possible in the current library?

From code perspective, I don't want to use a ServerCurrentCredential object because that will get populated with the current server (which I don't want to use). I have tried PasswordCredential too but that does require username and password which is not what we want from a server perspective. Ideally I would like to only point to a server (no password needed).

If that is not possible, I'll have to perform the test the right way: logon into another machine that is part of the test AD and run the code from there instead of running it from my dev machine.

Thanks,
Hisham

**Comment by antiduh** [comment]
You want to be able to pretend to be another user, and convince other network services that you're another user, without ever logging in as that user?

If that were possible, then I could put my laptop on your network and pretend to be your CEO and take all of your company's money.

Do you not see the inherent mistake you're making?

**Comment by Hochman85** [comment]
I never said "without ever logging in as that user (either by... or by..)". I actually said the opposite and clearly stated: "I'd like to force use another AD with OTHER CREDENTIALS" (valid ones of course so there is definitely username and password here!).

So back to your reply: as per my understanding you cannot put your laptop on our network and pretend to be our CEO or any other employee because you will have NO valid username / password to validate against our AD.

Scenario (again):
- Am logged in against my company's AD
- I want to ignore the current server (and Kerberos token) and instead use my TEST username and password against our TEST AD (not the company's and of course we are authenticating)
- When I get a Kerberos token from the TEST AD, I'll know the TEST username and password are valid (again not the company's so this is totally isolated)
- As stated, this is temporarily so at least I can continue developing on my dev machine without having to deploy to a VM each time I have to test against the TEST AD. It'll save us a lot of time.

**Comment by antiduh** [comment]
Microsoft's sspi api does not allow for authenticating against arbitrary AD servers, at least to the best of my knowledge. Feel free to browse the SSPI api and tell me how you'd expect to accomplish what you're trying to do natively. 

You can call PasswordCredential providing any *domain* you want, so long as that domain is either the domain your computer is joined to, or is a domain trusted by the domain your computer is joined to. 

https://social.technet.microsoft.com/Forums/en-US/48b6ecb5-2715-4af5-a7aa-d67148cdff1d/single-computer-login-to-multiple-domains?forum=winserverDS

A computer can be joined to only one domain at a time. Sspi operates within the context of the domain that your computer is joined against.

**Comment by Hochman85** [comment]
Thanks for your reply Kevin.

Yes of course a computer can be part of one domain only.

I think the second option (making sure the domain is trusted then switching to PasswordCredential) should do the job. In the meantime, I've switched to using a VM joined to the dev domain.

I have another question though which I am raising in a separate ticket.

Thanks.
