### ISSUE TITLE
This library is great and you're a great person for making it

### ISSUE THREAD

**Issue by mcgov** [antiduh/nsspi#7]
Also thank you for including good examples.

**Comment by antiduh** [comment]
Dang, thanks man. It's been a rough week, I needed that.

**Comment by mcgov** [comment]
Of course!

What are you working on now? Want any help?

-matthew

**Comment by antiduh** [comment]
Not much, just work stuff mostly. I've got a few ideas for projects but nothing too concrete yet. If you're looking to help, I want to try to add GSSAPI support to NSSPI; someone else did but never committed back their work (which is fine, just unfortunate). I don't have a good environment to test that against so I haven't looked into it too much yet. If you're curious, take a stab at it and let me know what you find.
